name: Requests a new Unity build image

inputs:
  version:
    description: Version of Unity to build (e.g.
    required: true
  changeset:
    description: Changeset of Unity to build (e.h.
    required: true
  path:
    description: Path to this repository
    required: true
    default: "./"
  token:
    description: GitHub access token with permissions to write the unity package
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to the container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Build and tag container
      shell: powershell
      run: |
        docker build `
          --build-arg UNITY_VERSION=${{ inputs.version }} `
          --build-arg UNITY_CHANGESET=${{ inputs.changeset }} `
          ${{ input.path }}unity `
          -t ghcr.io/playeveryware/unity:${{ inputs.version }}

    - name: Push image to registry
      shell: powershell
      run: |
        docker push ghcr.io/playeveryware/unity:${{ inputs.version }}
