name: Find the changeset number for a Unity version

on:
  workflow_call:
    inputs:
      version:
        description: "Version of Unity to lookup"
        required: true
        type: string
    outputs:
      changeset:
        description: "Changeset matching the Unity version"
        value: ${{ jobs.find-changeset.outputs.changeset }}

jobs:
  find-changeset:
    runs-on: [self-hosted]
    name: Find changeset for Unity ${{ inputs.version }}
    outputs:
      changeset: ${{ steps.lookup.outputs.changeset }}
    steps:
      - run: echo "::echo::off"
      - name: Lookup changeset
        id: lookup
        shell: powershell
        run: |
          $match = (Invoke-WebRequest -UseBasicParsing `
            -Uri "https://unity3d.com/get-unity/download/archive" `
            | Select-String 'unityhub://${{ inputs.version }}/([^"]*)')
          if (!$match) {
            echo "::error::Could not determine Unity changeset number for version ${{ inputs.version }}"
            exit 1
          }

          $changeset = $match.matches.groups[1].value
          echo ( "::notice::Found changeset " + $changeset + " for Unity version ${{ inputs.version }}" )
          echo ( "::set-output name=changeset::" + $changeset )
